In [4]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_validate, train_test_split
from numpy.linalg import svd
# conda install tensorflow
from tensorflow.keras import datasets
from sklearn.decomposition import PCA

In [6]:
train, test = datasets.mnist.load_data()
pca = PCA(n_components=.7)
xtrain, ytrain = train
N, M1, M2 = xtrain.shape
x_reduced = pca.fit_transform(xtrain.reshape(N, -1))

In [7]:
xtrain

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [8]:
x_reduced

array([[ 123.93258866, -312.67426202,  -24.51405176, ...,  250.24442545,
          46.166068  ,  100.33944406],
       [1011.71837587, -294.85703827,  596.33956104, ...,   18.36872214,
         232.0157561 ,  214.90041971],
       [ -51.84960805,  392.17315286, -188.50974943, ...,   -7.25159916,
        -130.065424  ,   86.447237  ],
       ...,
       [-178.0534496 ,  160.07821109, -257.61308227, ...,  -68.42260311,
        -370.34023033,  -27.20112081],
       [ 130.60607208,   -5.59193642,  513.85867395, ...,  -90.90778711,
         147.12510219,  442.79538593],
       [-173.43595244,  -24.71880226,  556.01889393, ..., -134.52185799,
         -71.20325505, -189.46459831]])

In [9]:
ytrain

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [13]:
%%time
pipe = Pipeline([
    ("pca",PCA(n_components=.7)),
    ("knc", KNeighborsClassifier(n_neighbors=5))
])

cv1 = cross_validate(pipe, x_reduced, ytrain, cv=3)

Wall time: 32.7 s


In [15]:
%%time
cv2 = cross_validate(KNeighborsClassifier(n_neighbors=5), x_reduced, ytrain, cv=3)

Wall time: 2min 42s


In [16]:
cv1

{'fit_time': array([0.55152178, 0.55395269, 0.45641851]),
 'score_time': array([11.25316834, 10.18614388,  9.73175955]),
 'test_score': array([0.93595, 0.93105, 0.9331 ])}

In [17]:
cv2

{'fit_time': array([0.78995013, 0.79056811, 0.8183496 ]),
 'score_time': array([52.22201276, 53.94279766, 53.93527579]),
 'test_score': array([0.9714 , 0.9699 , 0.97045])}

In [22]:
print(cv1['test_score'].mean())
print(cv2['test_score'].mean())

0.9333666666666667
0.9705833333333334


In [18]:
print("se puede apreciar que el modelo del pipe es mas rapido al aplicarle un pca y reducir la cantidad de informacion, pero en cuanto a precision se pierde un poco al momento de reducir la informacion")

se puede apreciar que el modelo del pipe es mas rapido al aplicarle un pca y reducir la cantidad de informacion, pero en cuanto a precision se pierde un poco al momento de reducir la informacion
