<h2 style="color:crimson">Ejercicio</h2>

**Entrenando un modelo con PCA**  
Considerando  `xtrain`, `ytrain` definido en las céldas de arriba, crea dos modelos: 
1. Un pipeline considerando PCA con `n_components=0.7` seguido de un modelo `KNeighborsClassifier` con `n_neighbors=5`
2. `KNeighborsClassifier` con `n_neighbors=5`

Realiza un *cross validation* con `cv=3`.
* ¿Qué resultados arroja cada modelo?
* ¿que ventajas tiene cada modelo?
* ¿Cuánto tarda en correr cada *cross-validation*?

In [27]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_validate, train_test_split
from numpy.linalg import svd
# conda install tensorflow
from tensorflow.keras import datasets
from sklearn.decomposition import PCA
import numpy as np

In [28]:
np.random.seed(3141)
train, test = datasets.mnist.load_data()   #importo la informacion
pca = PCA(n_components=.7)
xtrain, ytrain = train  #obtengo el train set
N, M1, M2 = xtrain.shape
x_reduced = pca.fit_transform(xtrain.reshape(N, -1))

In [29]:
xtrain

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [30]:
x_reduced

array([[ 123.93258866, -312.67426202,  -24.51405176, ...,  250.24442545,
          46.166068  ,  100.33944406],
       [1011.71837587, -294.85703827,  596.33956104, ...,   18.36872214,
         232.0157561 ,  214.90041971],
       [ -51.84960805,  392.17315286, -188.50974943, ...,   -7.25159916,
        -130.065424  ,   86.447237  ],
       ...,
       [-178.0534496 ,  160.07821109, -257.61308227, ...,  -68.42260311,
        -370.34023033,  -27.20112081],
       [ 130.60607208,   -5.59193642,  513.85867395, ...,  -90.90778711,
         147.12510219,  442.79538593],
       [-173.43595244,  -24.71880226,  556.01889393, ..., -134.52185799,
         -71.20325505, -189.46459831]])

In [31]:
ytrain

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [32]:
%%time
pipe = Pipeline([    #genero el pipe con pca y knc
    ("pca",PCA(n_components=.7)),
    ("knc", KNeighborsClassifier(n_neighbors=5))
])

cv1 = cross_validate(pipe, x_reduced, ytrain, cv=3)

Wall time: 34.1 s


In [33]:
%%time
cv2 = cross_validate(KNeighborsClassifier(n_neighbors=5), x_reduced, ytrain, cv=3)

Wall time: 2min 44s


In [34]:
cv1

{'fit_time': array([0.49585629, 0.5671792 , 0.60703564]),
 'score_time': array([12.18700719, 10.09491205, 10.01162267]),
 'test_score': array([0.93595, 0.93105, 0.9331 ])}

In [35]:
cv2

{'fit_time': array([0.79007602, 0.81039429, 1.26096058]),
 'score_time': array([53.02180862, 54.37927222, 53.77408218]),
 'test_score': array([0.9714 , 0.9699 , 0.97045])}

In [36]:
print(cv1['test_score'].mean())
print(cv2['test_score'].mean())

0.9333666666666667
0.9705833333333334


In [37]:
print("se puede apreciar que el modelo del pipe es mas rapido al aplicarle un pca y reducir la cantidad de informacion, pero en cuanto a precision se pierde un poco al momento de reducir la informacion")

se puede apreciar que el modelo del pipe es mas rapido al aplicarle un pca y reducir la cantidad de informacion, pero en cuanto a precision se pierde un poco al momento de reducir la informacion
